language: android
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
  - extra

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      before_script: chmod +x gradlew
      script: "./gradlew clean testDebug"

    - stage: build
      before_install:
        - openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
            -in android-release.jks.enc -out android-release.jks -d
      before_script: chmod +x gradlew
      script: "./gradlew assembleRelease"
#before_script:
#- chmod +x gradlew
#script:
#- "./gradlew clean testDebug"
#before_install:
#- openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
#  -in android-release.jks.enc -out android-release.jks -d
